# Generated by Django 3.2.15 on 2023-10-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Department Title')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('create_time', models.DateTimeField(verbose_name='enroll time')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (0, 'female')], verbose_name='gender')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department')),
            ],
        ),
    ]
