# Generated by Django 5.0.2 on 2024-02-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Age')),
                ('create_time', models.DateTimeField(verbose_name='start_time')),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='gender')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_01.department')),
            ],
        ),
    ]
