# Generated by Django 5.0.2 on 2024-03-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart',
            new_name='depart_id',
        ),
    ]
