# Generated by Django 5.0.2 on 2024-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_rename_depart_id_userinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account'),
        ),
    ]
