# Generated by Django 5.0.2 on 2024-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0004_alter_userinfo_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='FancyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('level', models.SmallIntegerField(choices=[(1, 'basic'), (2, 'premium'), (3, 'vip')], default=1, verbose_name='level')),
                ('status', models.SmallIntegerField(choices=[(0, 'taken'), (1, 'free')], default=1, verbose_name='status')),
            ],
        ),
    ]
