# Generated by Django 5.0.2 on 2024-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0005_fancynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
            ],
        ),
    ]
